version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - gocyclo
    - asasalint
    - bodyclose
  exclusions:
    generated: lax

issues:
  max-issues-per-linter: 100
  max-same-issues: 5
